# Generated by Django 6.0.2 on 2026-02-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=200, verbose_name='Variety / Hybrid Crosses')),
                ('seednuts_type', models.CharField(blank=True, max_length=20, verbose_name='Seednuts Produced (OPV/Hybrid)')),
                ('seednuts_count', models.PositiveIntegerField(default=0, verbose_name='Seednuts Produced Count')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='field_data.monthlyharvest')),
            ],
            options={
                'verbose_name_plural': 'Harvest varieties',
                'ordering': ['pk'],
            },
        ),
    ]
