# Generated by Django 6.0.2 on 2026-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0002_harvestvariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestvariety',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remarks'),
        ),
    ]
