# Generated by Django 6.0.2 on 2026-03-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0003_harvestvariety_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybriddistribution',
            name='seedlings_received',
            field=models.CharField(blank=True, max_length=50, verbose_name='No. of Seedlings Received'),
        ),
    ]
