# Generated by Django 6.0.2 on 2026-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0004_alter_hybriddistribution_seedlings_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollenproduction',
            name='pollen_variety',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pollen Variety'),
        ),
    ]
