# Generated by Django 6.0.2 on 2026-03-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0005_pollenproduction_pollen_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='culled_seedlings',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='date_harvested',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='date_sown',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='good_seedlings',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='ready_to_plant',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='seedlings_dispatched',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='seedlings_germinated',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='seednuts_harvested',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='seednuts_sown',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='source_of_seednuts',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='ungerminated_seednuts',
        ),
        migrations.RemoveField(
            model_name='nurseryoperation',
            name='variety',
        ),
        migrations.CreateModel(
            name='NurseryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seednuts_harvested', models.PositiveIntegerField(default=0, verbose_name='No. of Seednuts Harvested')),
                ('date_harvested', models.CharField(blank=True, max_length=50, verbose_name='Date Harvested')),
                ('date_received', models.CharField(blank=True, max_length=50, verbose_name='Date Seednuts Received')),
                ('source_of_seednuts', models.CharField(blank=True, max_length=200, verbose_name='Source of Seednuts')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='Type / Variety')),
                ('seednuts_sown', models.PositiveIntegerField(default=0, verbose_name='No. of Seednuts Sown')),
                ('date_sown', models.CharField(blank=True, max_length=50, verbose_name='Date Seednut Sown')),
                ('seedlings_germinated', models.PositiveIntegerField(default=0, verbose_name='No. of Seedlings Germinated')),
                ('ungerminated_seednuts', models.PositiveIntegerField(default=0, verbose_name='No. of Ungerminated Seednuts')),
                ('culled_seedlings', models.PositiveIntegerField(default=0, verbose_name='No. of Culled Seedlings')),
                ('good_seedlings', models.PositiveIntegerField(default=0, verbose_name='No. of Good Seedlings @ 1 ft tall')),
                ('ready_to_plant', models.PositiveIntegerField(default=0, verbose_name='No. of Ready to Plant (Polybagged)')),
                ('seedlings_dispatched', models.PositiveIntegerField(default=0, verbose_name='No. of Seedlings Dispatched')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='field_data.nurseryoperation')),
            ],
            options={
                'verbose_name_plural': 'Nursery batches',
                'ordering': ['pk'],
            },
        ),
    ]
