# Generated by Django 6.0.2 on 2026-03-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0006_remove_nurseryoperation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryoperation',
            name='date_ready_for_distribution',
            field=models.DateField(blank=True, help_text='Date when seedlings became ready for planting', null=True, verbose_name='Date Ready for Distribution'),
        ),
        migrations.AddField(
            model_name='nurseryoperation',
            name='distribution_remarks',
            field=models.TextField(blank=True, help_text='Final distribution notes/summary for terminal report', verbose_name='Distribution Remarks'),
        ),
        migrations.AddField(
            model_name='nurseryoperation',
            name='nursery_start_date',
            field=models.DateField(blank=True, help_text='Date when seednuts were first sown in the nursery', null=True, verbose_name='Nursery Start Date'),
        ),
    ]
