# Generated by Django 6.0.2 on 2026-03-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0007_nurseryoperation_date_ready_for_distribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurserybatch',
            name='culled_seedlings',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='date_sown',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='good_seedlings',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='ready_to_plant',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='seedlings_dispatched',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='seedlings_germinated',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='seednuts_sown',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='ungerminated_seednuts',
        ),
        migrations.RemoveField(
            model_name='nurserybatch',
            name='variety',
        ),
        migrations.CreateModel(
            name='NurseryBatchVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='Type / Variety')),
                ('seednuts_sown', models.PositiveIntegerField(default=0, verbose_name='No. of Seednuts Sown')),
                ('date_sown', models.CharField(blank=True, max_length=50, verbose_name='Date Seednut Sown')),
                ('seedlings_germinated', models.PositiveIntegerField(default=0, verbose_name='No. of Seedlings Germinated')),
                ('ungerminated_seednuts', models.PositiveIntegerField(default=0, verbose_name='No. of Ungerminated Seednuts')),
                ('culled_seedlings', models.PositiveIntegerField(default=0, verbose_name='No. of Culled Seedlings')),
                ('good_seedlings', models.PositiveIntegerField(default=0, verbose_name='No. of Good Seedlings @ 1 ft tall')),
                ('ready_to_plant', models.PositiveIntegerField(default=0, verbose_name='No. of Ready to Plant (Polybagged)')),
                ('seedlings_dispatched', models.PositiveIntegerField(default=0, verbose_name='No. of Seedlings Dispatched')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='field_data.nurserybatch')),
            ],
            options={
                'verbose_name_plural': 'Nursery batch varieties',
                'ordering': ['pk'],
            },
        ),
    ]
