# Generated by Django 6.0.2 on 2026-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supervisor', 'COS / Agriculturist'), ('admin', 'Senior Agriculturist'), ('superadmin', 'PCDM / Division Chief I'), ('sysadmin', 'System Administrator')], default='supervisor', max_length=20),
        ),
    ]
