# Generated by Django 6.0.2 on 2026-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsite',
            name='noted_by_label',
            field=models.CharField(blank=True, default='Noted by:', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='noted_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='noted_by_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='prepared_by_label',
            field=models.CharField(blank=True, default='Prepared by:', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='prepared_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='prepared_by_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='reviewed_by_label',
            field=models.CharField(blank=True, default='Reviewed by:', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='reviewed_by_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
