# Generated by Django 6.0.2 on 2026-03-17 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridizationrecord',
            name='date_noted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hybridizationrecord',
            name='date_prepared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hybridizationrecord',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hybridizationrecord',
            name='noted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hybridizationrecord',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hybridizationrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hybridizationrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('reviewed', 'Reviewed'), ('noted', 'Noted'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
    ]
