# Generated by Django 6.0.2 on 2026-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF Report'), ('csv', 'CSV Export'), ('excel', 'Excel Export')], max_length=10),
        ),
    ]
